services:
  mcp-office-docs:
    image: georgx22/mcp-office-docs:latest
    container_name: mcp-office-docs
    restart: always
    ports:
      - "8958:8958"
    environment:
      # Upload strategy: LOCAL saves to mounted /app/output; S3 uploads to AWS; GCS uploads to Google Cloud Storage
      UPLOAD_STRATEGY: LOCAL
      # The following AWS variables required only if UPLOAD_STRATEGY=S3
      AWS_ACCESS_KEY:
      AWS_REGION:
      AWS_SECRET_ACCESS_KEY:
      S3_BUCKET:
      # The following GCS variables required only if UPLOAD_STRATEGY=GCS
      GCS_BUCKET:
      GCS_CREDENTIALS_PATH: /app/config/gcs-credentials.json
    volumes:
      # Local output directory (required for LOCAL strategy)
      - ./output:/app/output
      # Custom Office templates (optional: template_4_3.pptx, template_16_9.pptx, template.docx)
      - ./templates:/app/templates
      # Config directory containing:
      #   - config.yaml (optional styling overrides for emails)
      #   - email_templates.yaml (dynamic email tool definitions – Mustache templates)
      - ./config:/app/config
    # Optional: healthcheck could be added later when MCP protocol ping endpoint is exposed
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8958/mcp"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3
