services:
  mcp-presentation:
    image: georgx22/mcp-office-docs:latest
    container_name: mcp-office-docs
    restart: always
    ports:
      - "8958:8958"
    environment:
      UPLOAD_STRATEGY: # Your upload strategy, either LOCAL or S3
      AWS_ACCESS_KEY: Your AWS access key # Required for S3 upload strategy
      AWS_REGION: Your AWS region, e.g. us-east-1 # Required for S3 upload strategy
      AWS_SECRET_ACCESS_KEY: Your AWS secret access key # Required for S3 upload strategy
      S3_BUCKET: Name of your AWS S3 bucket # Required for S3 upload strategy
    volumes:
      - <host_path>:/app/output # Directory to save created presentations to, required for LOCAL upload strategy
      - <host_path>:/app/templates # Directory with custom templates, if used
