# Dynamic email template tools configuration (Mustache-only)
# Location: /app/config/email_templates.yaml inside container.
# Base fields automatically added to EVERY template tool (do NOT declare them here):
#   subject (string, required), to (list[str]), cc (list[str]), bcc (list[str])
# Supported custom argument types:
#   string / str        -> plain text value
#   int / integer       -> integer value
#   float               -> floating point value
#   bool / boolean      -> boolean (true/false) usable as a Mustache section {{#flag}} ... {{/flag}}
#   list                -> list of strings (iterate with {{#listVar}}{{.}}{{/listVar}})
#   dict / object       -> mapping (access nested keys via dot syntax: {{meta.author}})
#   enum (via 'enum:' list) -> restrict accepted values (Literal[...] validation), supports default
# Defaults: supply 'default:'; for enum it must be one of the enum values. If required:true and default given,
#           the field acts like optional (default used if omitted).
# Raw HTML: only use triple braces ({{{var}}}) in template for variables you intend to contain HTML (e.g. rich_body).

templates:
  - name: conflict_check_form
    description: PRK Partners conflict check form for new matters and client engagements
    html_path: conflict_check.html
    annotations:
      title: Conflict Check Form (PRK Partners)
    args:
      - name: partner_name
        type: string
        required: true
        description: Attorney sending conflict check (full name)

      - name: clients
        type: string
        required: true
        description: The client(s) - one per line (Name, Id. No. or Name, date of birth for individuals)

      - name: client_group
        type: string
        required: false
        description: Client's group/holding name only

      - name: client_controller
        type: string
        required: false
        description: Name of client's ultimate controlling person(s) or entity(ies) in 1 line

      - name: business_sector
        type: string
        required: false
        description: Client's business sector or industry, name only

      - name: counterparties
        type: string
        required: false
        description: The counterparty(ies) involved in the matter (if any), one per line - (Name, Id. No. or Name, date of birth for individuals)

      - name: counterparty_group
        type: string
        required: false
        description: Name of counterparty's group/holding

      - name: counterparty_controller
        type: string
        required: false
        description: Name of counterparty's ultimate controlling person(s) or entity(ies) in 1 line

      - name: other_parties
        type: string
        required: false
        description: Other party(ies) relevant for conflict check, if any (Name, Id. No. or Name, date of birth for individuals)

      - name: service_scope_1
        type: string
        required: true
        enum: ["Banking & Finance", "Capital Markets", "Competition Law & State Aid", "Compliance a AML", "Corporate", "Dispute Resolution", "Energy Law", "Environmental Law", "ESG", "EU Law", "Information and Communication Technology", "Insolvency and Restructuring", "Insurance", "Intellectual Property", "Investment Incentives", "Labour Law & Employment", "Marketing & Media", "Mergers & Acquisitions", "Pharma & Life Sciences", "Public Procurement", "Real Estate", "Tax Advisory", "Trade and Commerce"]
        description: Primary subject matter/scope of PRK's services

      - name: conflict_situation
        type: string
        required: true
        enum: ["Proposal", "New confirmed mandate", "Change in parties to existing mandate"]
        description: Stage of the conflict check process

      - name: referral_from
        type: string
        required: true
        enum: ["Advokátní kancelář - jiná", "Direktoriáře", "Freshfields", "Klient", "Legal Business Club", "Lex Mundi", "Marketingová akce", "Ostatní", "Partneři", "Publikační činnost", "Semináře", "WEB"]
        description: Source of the referral (how the matter came to PRK)

      - name: referral_details
        type: string
        required: false
        description: Additional details about the referral source

      - name: referral_to_firm
        type: string
        required: false
        description: Information about potential referral to another law firm

      - name: notes
        type: string
        required: false
        description: Only important notes for conflict check (if any)
